### ISSUE TITLE
Open the airport information page by clicking on an airport in the map

### ISSUE THREAD

**Issue by N129BZ** [shanet/pirep#111]
It would be nice to have the application open up the airport information page when clicking on an airport on the sectional map

**Comment by shanet** [comment]
Hi @N129BZ, can you please elaborate more on this? When clicking on an airport on the map the current behavior is to open the airport drawer for quick viewing without needing to leave the map. Then from within the drawer, clicking on the "more" button will open the full airport page.

**Comment by N129BZ** [comment]
Probably the way I'm using the app.  For example - if you're in Sectional view, click on the Airports list item - none are visible unless you click on one or more of the three categories (public, private, restricted) where I guess my expectation would be since airports are the most-likely main feature of a sectional map, just clicking on an airport would open the airport information... similar to how an EFB would work - you click on an airport and you get the info popup for that airport.  Clicking on a specific category item on the left would add a differentiating marker on airports in that category

**Comment by shanet** [comment]
Last month I made the intentional change to only show "documented" airports (airports with some user-entered information) by default on the map. The idea being that there are ~20,000 airports and showing them all by default results in a less than useful initial view for new users to the website when most airports clicked on would contain no useful information. Ideally I want the new user flow to be "visit website, find useful information about local airports" and that's more difficult when you have to fiddle with filters and go searching for airports with some useful information written about them.

To see the other airports you're correct that you'd need to change the map's default filters to show public/private airports to see the "empty" ones. You can also search for an airport and it will open the drawer, even if not shown by the filter configuration.

I'm not fully convinced this is the right behavior as I know it can be confusing. It's a balancing act between displaying airports with information on them vs. every airport right out of the box. I'm hoping in time as more airports get information written about them the initial map view will become increasingly useful. However, it will always be the case that many airports simply have nothing interesting about them and accordingly not worth clicking on so why bother displaying them by default?

Commit that implemented this behavior from the previous behavior which displayed all airports by default: https://github.com/shanet/pirep/commit/3306e2d2f991e8c4d59e3e9683b70061c8dd97cc

**Comment by shanet** [comment]
This got me thinking that adding a transparent marker for airports so even when their marker is not visible through a selected filter it's still possible to click on the airport and have it open the drawer. It's not a perfect solution, but I think it may resolve some of the confusion around not being able to click on an airport when the right filter to display it isn't selected. Plus it was easy enough to implement so why not try it out?

**Comment by N129BZ** [comment]
Very nice!  Exactly what I was thinking about.
