### ISSUE TITLE
Add advanced search

### ISSUE THREAD

**Issue by XIIGage1** [shanet/pirep#179]
Hey! First of all, great site. I've been trying to find a good source of restaurants and other airport information that has useful and filterable information on it. Seems like everything aviation is 30 years old and not being updated.

To my question:

Curious if a filter can be added for runway length? Being able to filter out small GA airfields with small or unimproved runways would be useful for certain aircraft. Thanks for your hard work!

**Comment by shanet** [comment]
Hey @XIIGage1 thanks for the suggestion! I could see this being some type of an "advanced search" page where you could specify more exact criteria. I've avoided writing this for a while now since so far I've been building Pirep for me and I like clicking around a map to explore and find new stuff. But I also know others would rather simply search for exactly what they're looking for so I could see how a better search function would be helpful in those cases.

The current map page only allows for selecting tags. I'd be hesitant to add more functionality to that page out of fear of overcomplicating the UI for the base case and since it's already a busy page. But something like a link next to the existing search that went to another page with a more comprehensive search form could work well. That way users can pick if they want to explore the map or search for specific criteria.

My first guess at search options would be:

* Min runway length
* Runway type (paved, grass, dirt, etc. This info is currently in Pirep's database, but not shown anywhere on the website)
* Max field elevation
* Lighted runways
* Distance from a home airport or on a given sectional chart (probably the former)
* Exclude unmapped or private airports
* Include certain tags only
* Maybe include METAR data to filter out currently MVFR/IFR airports?
* Maybe something around upcoming event dates (for example airports with upcoming events in the next N days)
* Maybe airports with approaches? This info isn't currently in the Pirep database though so that would have a prereq of adding more parsing of the FAA database products.

Anything else that would be useful? I'm sure there's lots of other things too, but the first pass at this would be data already in the database.

**Comment by shanet** [comment]
This is available at https://pirep.io/airports/advanced_search now. I'll close this issue since its shipped but I'm always happy for user feedback.

**Comment by XIIGage1** [comment]
It works great! Already used it to find a few spots to stop.
