### ISSUE TITLE
Recurring / One Time event functionality

### ISSUE THREAD

**Issue by RedditPilot** [shanet/pirep#94]
Ability to define a one-time or recurring event (Every 1st-5th specific day of every month ie: 4th saturday of every month, Monthly, Weekly)
Expiration date for one-time events
Contact information including phone number, website, image of event flyer, details section
Option to filter map page by locations with upcoming events within a specified date range
An events listing page or sidebar would be great, you could list upcoming events within a specified date range within a specified radius of a location.  "All events in the next two weeks within 300 miles of KMCI"

Examples of events:
Recurring:
EAA Chapter 9000 Fly-In Breakfast at KPNT Every 2nd Saturday of month.  Recurring every month except OCT, NOV, DEC, JAN.

One-time:
VINTAGE DAY FESTIVAL & FLY-IN 2023 at GA2 June 3rd, 2023 9:00am - 6:00pm

**Comment by shanet** [comment]
Airports now support adding one-time and recurring events to them. This is displayed below the airport photos on its page. When an event is added it will also add the "events" tag to the airport. Airports with events can then be filtered for on the main map page by enabling the "events" tag filter.

I'd like to see how many events get added before building out another dedicated search page for events with more granular filters like timeframe and distance. I can see that being useful, but don't want to build it out until I have a better idea of exactly what the needs of it would be.

I'll close this as completed since the majority of the functionality is now live and open additional issues for further refinements to the event system. Thank you for the suggestion!
